package de.embl.iclm;

public class Help {

	/** Where the illustrated user manual is published (GitHub Pages, served from docs/). */
	protected static final String manualUrl = "https://embl-ic.github.io/opm-toolset/manual/";

	// help text for deskew active image
	protected static final String deskew = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.5 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2026.08.31 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deskew Image:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Deskew an image stack (as the OPM raw volume) that already opened in Fiji."
			+ "		<br> 3 parameters are essential for the deskewing: the <strong>XY pixel size</strong>,"
			+ "			the <strong>Z step size</strong>, and the <strong>OPM angle</strong>."
			+ "		<br>	With the in house built OPM system at EMBL IC, the typical values are:"
			+ "		<br>"
			+ "		<br>&nbsp <strong> XY pixel size</strong>: 116 nm "
			+ "		<br>&nbsp <strong> Z step size</strong>: 132.5 or 265 nm "
			+ "		<br>&nbsp <strong> OPM angle</strong>: 25°"
			+ "		<br>"
			+ "		<br> These parameters can also be loaded from setup files. "
			+ "			The setup file can be the metadata file normally saved next to the image file with name \"ExperimentalParameters.txt\". "
			+ "			Alternatively the setup file can also be the deskew matrix saved from previous operations,"
			+ "			with name like \"(OPM image name)_deskew.csv\" To save the deskew ( 3D affine transform ) matrix,"
			+ "			use the \"<strong>save deskew setting</strong>\" button located at the bottom of the dialog."
			+ "		<br>"
			+ "		<br> Depending on the input, several options are available to process dual channel images:"
			+ "		<br>"
			+ "		<br><strong> whole image</strong>:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "				No channle separation."
			+ "		<br><strong> fold by midline</strong>:&nbsp&nbsp&nbsp&nbsp"
			+ "				The right half of the image will be folded onto the left side as the 2nd channel."
			+ "		<br><strong> align with SIFT</strong>:&nbsp&nbsp&nbsp"
			+ "				2D rigid transform will be performed on the right half of the image,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "				based on SIFT features, to form the 2nd channel.  "
			+ "		<br><strong>only left</strong>:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"	
			+ "				Only the left half of the image will be processed."
			+ "		<br><strong>only right</strong>:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "				Only the right half of the image will be processed. (no flip of the image)."
			+ "		<br><strong>left & right separately</strong>:&nbsp&nbsp"
			+ "				The input image will be split horizontally in the middle and"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			processed as two independent images."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			(no flip of the right half of the image)."
			+ "		<br>"
			+ "		<br> For the SIFT-based alignment, it would require the input image to have sufficient common features in both channels"
			+ "			(left and right half of the image) to work properly. For example: a beads stack with clear signal in both channels."
			+ "			To save the align ( 2D rigid transform ) matrix,"
			+ "			use the \"<strong>save deskew setting</strong>\" button located at the bottom of the dialog."
			+ "		<br>"
			+ "		<br>2D Projection images can also be created upon selection(s), and displayed following creation of the deskewed 3D volume."
			+ "		<br>"
			+ "		<br>The 3D affine deskew matrix, and/or the 2D rigid align matrix can be exported and re-used later, "
			+ "			with the button \"<strong>save deskew setting</strong>\". Upon clicking, a separate dialog will open and ask for a folder, "
			+ "			in which to save the matrix as .csv files. The file name has a regular expression part <strong>&lt image name&gt</strong>,"
			+ "			that will be replaced with the image name. The matrix will be saved as comma separated values, "
			+ "			which can be read or modified offline."
			+ "		<br>"
			+ "		<br>The <strong>preivew</strong> check box provide live deskew preview features."
			+ "		<br>It would only work with GPU-based processing. Upon previewing,"
			+ "  		the GPU memory will be measured and the input image will be downsampled so that it can fit into the GPU memory,"
			+ "  		in together with the deskewed volume. The downsampling will be equal in X,Y, and Z axis,"
			+ "  		so that the projection views will still reflect the correct geometry."
			+ "		<br>The preview images, both deskewed volume and projection(s),"
			+ "  		should have &quot preview&quot in their image titles."
			+ "  		This keyword is used later to close all previewing images when" 
			+ "  		<strong>OK</strong> or <strong>Cancel</strong> button is pressed."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: The input raw image volume stores slices as time frames."
			+ "			Therefore, The T and Z dimension will be and should be swapped before any operation on the input data."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: The deskew process is 3D affine transformation."
			+ "			The transformation matrix is computed based on the 3 essential input parameters mentioned previously."
			+ "			The transform will be performed on the GPU with CLIJ and imglib2 library, if a suitable GPU is available."
			+ "			If not, or the GPU processing temptation failed, the transform will be performed on CPU, with TransfromJ library."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: It is generally hard to fit the original raw data into GPU all at once."
			+ "  		Therefore, the input volume will be first separated along X axis,"
			+ "			which is the axis that is not changed by the 3D affine transformation."
			+ "  		The X partitions will then be processed on GPU in a sequential manner."
			+ "  		The input partitions and deskewed output partitions will be stored in computer RAM."
			+ "			The deskewed outputs will then be combined together to finish the whole process."
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: The SIFT based alignment parameters are predefined."
			+ "			When computing from input image, an alignment check image will be presented."
			+ "			The image will be a maximum Z projection of deskewed image of 3 channels:"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			&nbsp&nbsp <strong>1</strong>: left side"
			+ "			&nbsp&nbsp <strong>2</strong>: right side flipped"
			+ "			&nbsp&nbsp <strong>3</strong>: right side SIFT aligned"
			+ "		<br> The computed 2D rigid transform matrix will be reported to Fiji console."
			+ "			A description in terms of how much rotation, and translation in X and Y axis"
			+ "			will also be reported. If the rotation exceed 0.5°, or X shfit exceed 80 pixels,"
			+ "			or Y shfit exceed 30 pixels, the alignment would be considered wrong."
			+ "			A warning message will be displayed in Fiji log window."
			+ "			However, the alignment will still be performed."
			+ "			But one should consider using a different sample image,"
			+ "			or use \"fold by midline\" option for channel operation."
			+ "		<br>"
			+ "		<br><strong>Known issue 1</strong>: Live preview might create all white/black images,"
			+ "			This is normally resulting from the Brightness/Contrast setting is not tuned."
			+ "			Often on the first run, or after changes of parameters,"
			+ "			the resulting pixel values are outside the range of curret displaying range"
			+ "		<br>"
			+ "		<br><strong>Known issue 2</strong>: SIFT align with previewing might be not working the same"
			+ "			as the raw input volume, because of the downsampling. "
			+ "			Anyway, the alignment matrix will not be saved with preview run."
			+ "			It only saving with real deskew run, i.e.: <strong>OK</strong> button pressed.";
			
	/** One paragraph for every dialog with section headings: they fold. A compile-time constant. */
	protected static final String FOLDS = "<br><br><strong>Sections</strong>: click a bold heading (&#9660;) to fold"
			+ " its section away, and again (&#9658;) to bring it back. A dialog too tall for the screen folds its"
			+ " largest sections until it fits, and every dialog opens folded the way it was last left.";

			protected static final String batchDeconvolution = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.6 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Batch Processing - Deconvolution:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "Deconvolve every volume in a folder, or build an experimental PSF from every bead volume in it."
			+ "<br><br><strong>Input setup</strong>: the <strong>operation</strong>, the folder, and a file name filter; tick <strong>recursive</strong> to look below the folder too."
			+ "<br><br><strong>Deconvolution</strong>: the PSF TIFF, the method, the number of iterations and the regularization. The same settings as <strong>Deconvolution &gt; Richardson-Lucy Deconvolution</strong>, whose help describes them."
			+ "<br><br><strong>Experimental PSF</strong>: how beads are found and averaged. The same settings as <strong>Deconvolution &gt; PSF from Beads Image</strong>, whose help describes them. The raw geometry deskews a raw bead volume first."
			+ "<br><br><strong>Output setup</strong>: the result folder, or the data folder itself; an existing result is skipped or overwritten. A run can be stopped cleanly with <strong>Batch Processing &gt; Terminate...</strong>."
			+ FOLDS
			+ "</html>";

	// help text in html format
	protected static final String batch = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.6 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Batch Processing - Deskew:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "Deskew every raw OPM volume in a folder, and write the results as deflated TIFF, OME-Zarr, or both."
			+ "<br><br><strong>Input setup</strong>: the folder holding the raw volumes (\".tif\"/\".tiff\"). Tick <strong>recursively check sub-folders</strong> to look below it too. The file name <strong>include</strong> and <strong>exclude</strong> lists filter by name; separate several with \",\"."
			+ "<br><br><strong>Deskew parameters</strong>: read from ExperimentalParameters.txt beside the data, or typed in with <strong>overwrite with manual input</strong>. See the help of <strong>Deskew Image</strong> for what they mean."
			+ "<br><br><strong>Channels</strong>: how each file's two mirrored camera halves become results. The <strong>channel option</strong> handles one file; <strong>combine matching _Channel#### files</strong> builds one result from the files of one time point, with the sources in slot order. <strong>[-] [+]</strong> shortens and lengthens that list. An <strong>align matrix</strong> comes from <strong>Utilities &gt; Channel Alignment</strong>."
			+ "<br><br><strong>Projection</strong>: the axes and types written beside each deskewed TIFF volume. An OME-Zarr always carries all six (max and mean along X, Y and Z)."
			+ "<br><br><strong>Output setup</strong>: the result folder, or a \"result\" folder inside the input when left empty. With <strong>separate results to sub-folders</strong> each view has a folder of its own (\"deskew\", \"maxZ\", ...). An existing result is skipped or overwritten; a file cut off part way is never kept as a result."
			+ "<br><br><strong>reproduce input folder structure</strong>, with sub-folders checked: each sub-folder's results go to the same sub-folder under the result folder - input&#92;A&#92;B&#92;x.tif to &lt;result folder&gt;&#92;A&#92;B. Unticked, every result goes into the result folder itself. Each acquisition folder gets an OME-Zarr dataset of its own either way, named after it. Saving to the same (data) folder always keeps the sub-folders apart, so the box is greyed there, and without sub-folders there is no tree to reproduce."
			+ "<br><br><strong>show combined movie with batch processing progress</strong> opens the run in the <strong>OPM Data Viewer</strong> as it is written: the <strong>projection view</strong> and the <strong>deskewed volume</strong>, both as virtual stacks that grow as time points arrive. Materialise from the viewer when a copy in memory is wanted."
			+ "<br><br>A run can be stopped cleanly with <strong>Batch Processing &gt; Terminate...</strong>; the log beside the results records what was done."
			+ FOLDS
			+ "</html>";

	protected static final String projectionBatch = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.6 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Batch Processing - Generate Projection Image:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "Write maximum and mean projections along X, Y and Z for every volume in a folder."
			+ "<br><br><strong>input type</strong>: an <strong>already deskewed volume</strong> is projected as it is; a <strong>raw OPM volume</strong> is deskewed first, with the geometry below it."
			+ "<br><br><strong>Channels</strong>: how the two camera halves in each volume are treated before projecting - the same choices as Batch Deskew. They apply to a raw volume and to a whole-width deskewed one alike, because the deskew shear moves Y and Z only and the halves stay side by side. A volume that already has its channels (a composite) is projected per channel under <strong>whole image</strong>."
			+ "<br><br><strong>Output setup</strong>: projections are written as deflated TIFF, named &lt;volume&gt;-maxZprojection.tif and so on, in one folder per view when results are separated. OME-Zarr is not offered here: a dataset stores its volume, and <strong>Batch Processing &gt; Deskew</strong> already writes one with all six projections."
			+ FOLDS
			+ "</html>";

	protected static final String channelOperation = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.6 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Batch Processing - Channel Operation:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "Split, flip, align and reorder the camera halves of results that are already deskewed. Nothing is deskewed here."
			+ "<br><br><strong>result folder</strong>: found the way the <strong>OPM Data Viewer</strong> finds it - TIFF results with one sub-folder per view or all views in one folder, and OME-Zarr datasets. The line below it says what was found."
			+ "<br><br><strong>OME-Zarr</strong>: a dataset keeps its halves unaligned and applies the alignment when it is viewed, so only its alignment metadata is replaced, after one confirmation. No pixel is read or written, and the original .zattrs is kept as .zattrs.original."
			+ "<br><br><strong>TIFF</strong> (plain, BigTIFF or deflated): the ticked views are processed. A box is greyed where no result can supply that view. When a result has its <strong>deskewed volume</strong>, every projection is recomputed from the operated volume, which is exact. Without it only a Z projection can be operated: an X or Y projection has already collapsed the plane the alignment is defined in."
			+ "<br><br><strong>Channels</strong>: the same controls as Batch Deskew. <strong>input layout</strong> says whether a result is a whole camera width (split it) or an existing channel hyperstack; auto detection decides by the channel count."
			+ "<br><br>A result that <strong>already has its channels</strong> can be reordered or thinned with no matrix at all - its halves were flipped and aligned when it was written. A matrix given for one is applied <em>on top</em> of that and cannot undo it; to change an alignment, go back to the whole-width result or to the OME-Zarr, where the alignment is metadata. Its channels take the slots in turn (_Channel0001-left, -right, _Channel0002-left, ...), so every one of them can be chosen, reordered or dropped. No OME-Zarr is written from such a result: there are no unflipped halves left to store."
			+ "<br><br><strong>Output setup</strong>: deflated TIFF keeps the input's names and layout, so the result opens in the viewer as a dataset. OME-Zarr stores the unflipped halves and records the alignment, the flip and the slot order as metadata: the viewer shows the operated result without a resampled pixel on disk. Results go beside the input, in &lt;result folder&gt;-channel-operation, unless another folder is given - never inside the folder being read."
			+ FOLDS
			+ "</html>";

	protected static final String formatConversion = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.6 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Batch Processing - Format Conversion:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "Change the storage format and nothing else: the pixels that come out are the pixels that went in. Nothing is deskewed, flipped or aligned."
			+ "<br><br><strong>data folder</strong>: found the way the <strong>OPM Data Viewer</strong> finds it, plus every other TIFF volume - in practice the raw acquisition BigTIFFs. One TIFF file can be named instead of a folder. The line below says what was found."
			+ "<br><br><strong>What converts to what</strong>:"
			+ "<br>&nbsp; - a TIFF volume that is not yet deflated: to deflated TIFF, OME-Zarr, or both;"
			+ "<br>&nbsp; - a deflated TIFF: to OME-Zarr only. Deflated to deflated would only copy it, and is skipped;"
			+ "<br>&nbsp; - a deskewed TIFF result: to one OME-Zarr dataset over all its time points;"
			+ "<br>&nbsp; - an OME-Zarr dataset: to deflated TIFF, one volume per time point, in the layout the viewer reads as a TIFF result."
			+ "<br><br>Deflate always runs at level 1, the fastest: this data compresses about as well at any level, and a slower level only costs time."
			+ "<br><br>The input is streamed a plane or a slab at a time, so a volume larger than memory converts. A classic TIFF is capped at 4 GB, which is checked before anything is written."
			+ FOLDS
			+ "</html>";

	// help text in html format

	protected static final String live = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.6 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2026.09.07 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Live Deskew - setup:</h2> "
			+ "		<strong>Illustrated manual</strong>, with a worked example (beads, then a"
			+ "			time lapse), every option explained and the live preview:"
			+ "		<br> <a href=\"" + manualUrl + "live-deskew.html\">" + manualUrl + "live-deskew.html</a>"
			+ "		<br> A single-file offline copy can be downloaded from the same page."
			+ "		<h3>Usage:</h3> "
			+ "			Deskew an acquisition while the microscope is still writing it."
			+ "		<br> The same settings, in the same sections, as <strong>Deskew Batch"
			+ "			Processing</strong>; that command does a folder, this one does a folder"
			+ "			that is still filling up."
			+ "		<br>"
			+ "		<br> The dialog has two depths. <strong>simple mode</strong> shows what is"
			+ "			decided once per session - which channels come out, where they go."
			+ "		<br> <strong>advanced mode</strong> reveals what is decided once per"
			+ "			microscope: the TCP port, the folder filters, the interpolation kernel."
			+ "		<br> Advanced values are hidden, never reset."
			+ "		<br>"
			+ "		<br> A field that another tick makes meaningless is greyed out rather than"
			+ "			silently ignored."
			+ "		<br>"
			+ "		<br> Click a bold section heading (&#9660;) to fold it away, and again (&#9658;)"
			+ "			to bring it back; the setup opens folded the way it was last left."
			+ "		<h3>Input setup:</h3>"
			+ "			<strong>listen to TCP/IP port</strong> accepts one file path per line."
			+ "		<br> The folder each path points into is searched for"
			+ "			<i>ExperimentalParameters.txt</i>."
			+ "		<br> <strong>also watch the folder from the announced file path</strong>"
			+ "			also follows new file-system events and enumerates what is already on disk there."
			+ "		<br> <strong>watch folder</strong> follows one folder whether or not"
			+ "			anything is announced over TCP; selecting it turns TCP/IP off."
			+ "		<br> These give exactly three modes: TCP/IP only, TCP/IP plus its announced"
			+ "			folder, or folder only."
			+ "		<br> A TIFF is sampled every 250 ms and must remain unchanged for one"
			+ "			continuous second. Its IFD and strip/tile offsets are then checked against EOF."
			+ "		<br> A processing I/O failure is retried twice after five seconds. After the"
			+ "			third failure it remains in the failed list and is reported in the Fiji Log."
			+ "		<br> <strong>file name include / exclude</strong> filter by name;"
			+ "			separate multiple fragments by \",\"."
			+ "		<h3>Deskew parameters:</h3>"
			+ "			The geometry is read from the acquisition's"
			+ "			<i>ExperimentalParameters.txt</i> by default."
			+ "		<br> Until it is known, volumes are queued and none is processed, so a"
			+ "			time point can never be deskewed with the previous run's numbers."
			+ "		<br> <strong>overwrite with manual input</strong> uses the three fields"
			+ "			below instead, and greys out the parameter file."
			+ "		<h3>Channels:</h3>"
			+ "			<strong>combine matching _ChannelNNNN files</strong> treats the files"
			+ "			of one time point as one multi-channel result."
			+ "		<br> Each output channel picks a camera half - left, right or whole -"
			+ "			of one acquisition channel, or is skipped."
			+ "		<br> Live processing waits until every acquisition-channel file implied by"
			+ "			this selection is complete before it starts the combined time point."
			+ "		<br> <strong>flip and align</strong> says which half is mirrored onto the"
			+ "			other, using the <strong>align matrix</strong> if one is given."
			+ "		<h3>Projection:</h3>"
			+ "			Which orthogonal views to produce, and how to reduce along the axis."
			+ "		<br> Simple mode always uses the maximum; advanced mode offers the mean too."
			+ "		<br> An OME-Zarr dataset carries all six projections inside itself"
			+ "			whatever is ticked here."
			+ "		<h3>Output setup:</h3>"
			+ "			<strong>format</strong> defaults to OME-Zarr, which is what makes a"
			+ "			preview of a run in progress possible: its time points commit one at a"
			+ "			time, so a reader can follow it safely."
			+ "		<br> <strong>show live projection view</strong> and <strong>show live"
			+ "			deskewed volume</strong> open the run in the <strong>OPM Data Viewer</strong>,"
			+ "			one window per projection plus the 5-D volume, and extend them in place as"
			+ "			each time point is written - the windows keep their size, zoom and"
			+ "			display ranges."
			+ "		<br> <strong>virtual</strong> reads planes as they are needed. Leave it on: a"
			+ "			materialised preview loads everything before the window opens and cannot"
			+ "			follow new time points. The volume preview is always virtual."
			+ "		<br> A run writing OME-Zarr is previewed from the store; a TIFF-only run is"
			+ "			previewed from its result files once each one is complete."
			+ "		<br> <strong>reproduce input folder structure</strong>, with a <strong>save"
			+ "			to</strong> folder: each acquisition's results go under that folder at the"
			+ "			input folder's own path, less its drive, in a <strong>result</strong> folder -"
			+ "			E:&#92;OPM&#92;run_0&#92;... saved to I:&#92;out goes to I:&#92;out&#92;OPM&#92;run_0&#92;result. The"
			+ "			same for every time point, acquisition and session. Unticked, every"
			+ "			acquisition's results go into the <strong>save to</strong> folder itself."
			+ "		<br>"
			+ "		<br> Press <strong>Escape</strong>, or use <strong>Batch Processing &gt;"
			+ "			Terminate...</strong>, to stop a run at its next safe point."
			+ "</html>";

	protected static final String terminate = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.6 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Running Batch Processing(s):</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Stop a batch run that is already going, without killing Fiji."
			+ "		<br>"
			+ "		<br> Every long-running command under <strong>Batch Processing</strong>"
			+ "			registers itself while it runs and is listed here:"
			+ "		<br> Deskew, Generate Projection Image, Channel Operation, Deconvolution"
			+ "			and Format Conversion."
			+ "		<br>"
			+ "		<br> Select one or more and press <strong>Terminate</strong>."
			+ "		<br> Shift-click selects a range; ctrl-click adds or removes one row."
			+ "		<br>"
			+ "		<br> Stopping is <strong>cooperative</strong>, and that is the point."
			+ "		<br> Each run unwinds at its next safe point - after the plane, chunk or"
			+ "			time point it is writing has been finished and closed."
			+ "		<br> So a terminated run leaves the same files on disk that a shorter"
			+ "			completed run would, and can be resumed."
			+ "		<br>"
			+ "		<br> Killing Fiji or ending the process instead cuts the writers off"
			+ "			wherever they happen to be, which is how a half-written chunk or a"
			+ "			truncated TIFF is made."
			+ "</html>";

	protected static final String watch_folder = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Folder Watcher: setup watcher</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Set up a watcher to monitor a folder for new image file to be created."
			+ "		<br>"
			+ "		<br> Specify a folder that the watcher need to monitor for file changes."
			+ "		<br> It is possible to also process files that already exist in the folder that being watched."
			+ "		<br> The <strong>max file writing delay</strong> defines how long "
			+ "			the watcher will wait from the last FILE MODIFIED event to conclude that"
			+ "			the writting process of the file is completed. And thus can be opened and processed safely."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: sub-folders are ignored from watching."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: A complete file save process normally consist of a FILE CREATED event,"
			+ "		<br> followed by several FILE MODIFED events, while image data are kept writting into the file."
			+ "		<br> Therefore, a delay will be neccessary to identify writing completed files";
	
	
	// help text in html format
	protected static final String watch_process = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Folder Watcher: setup processing</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Set up the processing parameters,"
			+ "		<br> when a new file creation is detected by the folder watcher."
			+ "		<br> The parameters are the same as in <strong>Deskew Batch</strong> command."
			+ "		<br> Check there the help text for a more detailed description of the parameters.";
	
	
	// help text in html format
	protected static final String tcpip = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>TCP-IP Listener:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Set up a listener to receive the full path of file created through TCP-IP socket."
			+ "		<br>"
			+ "		<br> Specify the TCP IP port number that the full file path will be sent through."
			+ "		<br> The rest of the parameters are the same as in <strong>Deskew Batch</strong> command."
			+ "		<br> Check there the help text for a more detailed description of the parameters."
			+ "		<br>"
			+ "		<br><strong>Note</strong>: There is no implementation that closes the listener."
			+ "		<br> Once it's up and running, it will keep listening to the specified port until Fiji exit.";
		
	
	// help text in html format
	protected static final String projection = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Projection:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Create projection image(s) of selected axis with selected type."
			+ "		<br>"
			+ "		<br> It takes an active image that already opened in Fiji as input."
			+ "		<br> The image need to be a 3D image stack."
			+ "		<br>"
			+ "		<br> The projection image(s) created will be labeled with projection axis"
			+ "			and type in the title(s):"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp "
			+ "			e.g.: -maxZ, -minZ, -avgZ, sumZ, -medZ, -stdZ"
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: The projection image(s) will have the same bit depth"
			+ "			as the input image, except for sum projection."
			+ "		<br> Sum projection will be in 32-bit image format to account for large pixel values."
			+ "		<br> Pixel values of the mean and standard deviation projections will be rounded to integer."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: median and standard deviation projection "
			+ "			of X- and Y- axis are not implemented for GPU processing."
			+ "		<br> As a workaround, a permuted volume is first created to transpose the original"
			+ "			X- or Y- axis to the new Z axis."
			+ "		<br> And then a Z projection is performed on GPU to fulfill the desired projection."
			+ "		<br> For X-projection, the ZYX permutation is performed."
			+ "		<br> For Y-projection, the XZY permutation is performed."
			+ "		<br>"
			+ "		<br><strong>Known issue</strong>: "
			+ "		median projection of more than 1000 voxel in the projection axis is not possible on GPU."
			+ "		<br> As a work around a less precise version is implemented as: first compute mean values in small range,"
			+ "		<br> for example every 2 or 3 voxels, and then the median value of these mean values are computed."
			+ "		<br> Median projection on CPU has no such limitation, but normally are slower.";

	
	
	// help text in html format
	protected static final String permutation = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Permutation:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Perform axis permutation on 3D volume."
			+ "		<br>"
			+ "		<br> Flip of axis can be performed prior to axis permutations."
			+ "		<br> The <strong>fold X</strong> option means to fold X axis by midline."
			+ "		<br> This will form a 2-channel image, same to the <strong>fold by midline</strong>"
			+ "		<br> channel option in deskew image command."
			+ "		<br>"
			+ "		<br> The permuted image created will be labeled as such:"
			+ "		<br>&nbsp&nbsp&nbsp <strong> -> Z[X]Y' </strong>"
			+ "			means an original <strong>XYZ</strong> volume permuted to <strong>ZXY</strong> volume."
			+ "		<br>&nbsp&nbsp&nbsp <strong>Y'</strong> means Y axis is flipped prior to permutation."
			+ "		<br>&nbsp&nbsp&nbsp <strong>[X]</strong> means X axis is folded."
			+ "		<br>"
			+ "		<br><strong>Note</strong>: In ImageJ or Fiji, "
			+ "			the default image dimension order is <strong>XY</strong>C<strong>Z</strong>T."
			+ "		<br> For 3D image volume without multiple channel or time frames,"
			+ "		<br> the <strong>1st</strong> axis is <strong>X</strong> axis, "
			+ "			the <strong>2nd</strong> axis is <strong>Y</strong> axis, "
			+ "			and the <strong>3rd</strong> axis is <strong>Z</strong> axis "
			+ "			(still <strong>4th</strong> behind the scene)."
			+ "		<br> upper left corner of the 1st Z slice is recongnized as the coordinate origin."
			+ "		<br> X axis pointing from left to right."
			+ "		<br> Y axis pointing from top to bottom."
			+ "		<br> Z axis pointing from front to back.";
	
	
	// help text in html format
	protected static final String sift = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>SIFT Alignment of Dual-Chnannel OPM Image:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Perform SIFT feature extraction and alignment on 2D images."
			+ "		<br>"
			+ "		<br> Check SIFT feature with parameters:";

	
	
	// help text in html format
	protected static final String transform = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Transform:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Perform 3D transformations on active image "
			+ "		<br>"
			+ "		<br> This command takes an image that already opened in Fiji,"
			+ "			and perform 3D transformations to it."
			+ "		<br> The transformation could be translation, scaling, rotation,"
			+ "			and shearing, of any specified axis."
			+ "		<br>"
			+ "		<br> Click on the <strong>+</strong> button to add a new transformation option."
			+ "		<br> The new transformation option consist of 5 setup parameters:"
			+ "		<br> &nbsp <strong>apply</strong>: whether to apply the transformation;"
			+ "		<br> &nbsp <strong>transform</strong>: transformation type;"
			+ "		<br> &nbsp <strong>axis</strong>: transformation along which axis;"
			+ "		<br> &nbsp <strong>value</strong>: transformation value;"
			+ "		<br> &nbsp <strong>show result</strong>: whether to display transformed image of this transformation;"
			+ "		<br>"
			+ "		<br> New transformation options can be added right after previous one "
			+ "			by clicking again the <strong>+</strong> button."
			+ "		<br>"
			+ "		<br> If <strong>Apply</strong> button is pressed,"
			+ "			then transformation(s) will be performed from top down,"
			+ "			and display result images for each transformation step that with <strong>show result</strong> checked."
			+ "		<br>"
			+ "		<br> Alternatively if <strong>Apply in Reverse Order</strong> button is pressed,"
			+ "			the transformation(s) will be performed from bottom up."
			+ "		<br>"
			+ "		<br> If <strong>inverse</strong> box is checked,"
			+ "			then the inverse matrix of the combined transformation matrix will be applied."
			+ "		<br>"
			+ "		<br> The transformation options can be saved to .json files in a human readable manner."
			+ "			And can be later loaded back to restore the transformations."
			+ "		<br>"
			+ "		<br> Alternatively the combined transformation matrix can be saved as .csv file."
			+ "			Thus saved transformation matrix file can also be used for deskew operations."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: Translation along X, Y, or Z axis follows ImageJ axis directions."
			+ "			value denotes shift for how many pixels."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: Negative value with scaling along X, Y, or Z axis,"
			+ "			means flip that axis or mirror transformation."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: Rotation along X, Y, or Z axis follows right hand rule."
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp for example: rotation along Z axis means clockwise rotation in the XY plane."
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp value denotes degree of rotation. Negative value then means reverse rotation."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: Shearing need to specify two axis to be clear."
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp Shearing in Y axis along Z axis for value 0.5 means:"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp Y(new) = Y(old) + 0.5* Z(old)"
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: The deskew process of OPM data is basically the sequential result of the following 3 transformations:"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp 1st:&nbsp shear Y along Z for (Z step size * cosθ);"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp 2nd: scale Z for (Z step size * sinθ / XY pixel size);"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp 3rd:&nbsp rotate around X for -θ;";
	

	// help text in html format
	protected static final String PSF = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.5 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2026.08.31 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deconvolution: Generate PSF from Beads Image(s)</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Average beads from image stack(s) to generate experimental PSF."
			+ "		<br>"
			+ "		<br> It works with either an active image opened in Fiji, or image files saved on disk."
			+ "		<br>"
			+ "		<br> If there's no image open in Fiji, the active image selection option will be omitted."
			+ "		<br> If <strong>load from file</strong> box is checked, active image will also be ignored."
			+ "		<br> The <strong>folder path</strong> expecting a folder that contains the beads image(s)."
			+ "		<br> If <strong>including subfolder(s)</strong> box is checked, "
			+ "		<br> all sub-folders will be recursively searched to locate \".tif\" and \".tiff\" images,"
			+ "		<br> that will be loaded."
			+ "		<br>"
			+ "		<br> <strong>image type</strong> specifies whether the input beads image is deskewed, or not."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The processing steps are different for deskewed and raw volumes:"
			+ "		<br>"
			+ "		<br>&nbsp&nbsp&nbsp	<strong>deskewed volume</strong>: "
			+ "			The local maxima points will be generated directly from the input deskewed volume;"
			+ "		<br>"
			+ "		<br>&nbsp&nbsp&nbsp	<strong>OPM raw volume</strong>:"
			+ "			The input image will first be deskewed, according to parameters in <strong>prepare beads image</strong>."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The local maxima points will be generated from the deskewed volume,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			and mapped back to the raw volume through inveresed transformation."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The crop of sub-volumes surrounding each local maxima locations,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			will thus be performed in the raw OPM volume."
			+ "		<br>"
			+ "		<br>&nbsp&nbsp&nbsp <strong>auto detection</strong>:"
			+ "			will try to check the image type automatically, and determine possible deskew parameters."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			This is based on checking the appearance of the max-projected YZ orthogonal view of the image."
			+ "		<br>"
			+ "		<br> <strong>channel layout</strong> can treat the input as one channel, or split packed"
			+ "		<br> mirrored left/right camera halves into independent channel PSFs. The right half can"
			+ "		<br> be horizontally flipped before bead detection and PSF generation. Files carrying"
			+ "		<br> different <strong>_Channel####</strong> tokens are also averaged independently."
			+ "		<br>"
			+ "		<br>"
			+ "		<br> <strong>prepare beads image</strong> button opens a second dialog"
			+ "			to specify the processing on the beads image(s)."
			+ "		<br>"
			+ "		<br> <strong>Load beads center position from ROI Manager</strong>: is to help semi-manual beads detection."
			+ "		<br> If selected, it will skip all beads detection related steps."
			+ "		<br> Instead, all entries currently presented in ROI Manager will be taken as the beads center position."
			+ "		<br> Therefore, it enables modification and manual selection of beads by user."
			+ "		<br> Please note, it would be better to use point ROI to denote beads center positions."
			+ "		<br> And as the position should be for 3D, also check to make sure the Z slice position is "
			+ "		<br> correctly set and associated with the ROI entries."
			+ "		<br>"
			+ "		<br>"
			+ "		<br> <strong>XY radius</strong> and <strong>Z radius</strong>:"
			+ "			specify the size of each dimension of the beads sub-volumes,"
			+ "		<br> that surrounding the detected local maxima point from previous steps."
			+ "		<br> Note the value here should corresponding to <strong>raiuds</strong>,"
			+ "		<br> The size of such defined volume will be:"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			width:&nbsp X radius ×2 + 1;"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			height: Y radius ×2 + 1;"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			depth:&nbsp Z radius ×2 + 1;"
			+ "		<br> In addition, for the <strong>OPM raw volume</strong> case,"
			+ "			the size will be corresponding to the deskewed volume."
			+ "		<br> This means that after inversed transform back to the coordinates of the raw volume,"
			+ "		<br> the corresponding crop volume will also change."
			+ "		<br> Therefore, the minimum circumscribed bounding box in the raw volume,"
			+ "		<br> that contains the desired deskewed volume will be cropped."
			+ "		<br> There is no manipulation or interpolation of pixel values in this procedure,"
			+ "		<br> but only recalculation of the coordinates and boundaries to be cropped."
			+ "		<br>"
			+ "		<br> <strong>~ bead count</strong>:"
			+ "			indicate the desired beads number within the image, or ROI range."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			It's implemented in a way that even more local maxima are present in the data,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			still roughly the indicated number of peaks will be picked out."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			Peaks with higher SNR are more likely to be detected and kept."
			+ "		<br>"
			+ "		<br> <strong>point to ROI Manager</strong> option only matters for the active image case."
			+ "		<br> Upon checked, coordinates of all the detected peaks (local maxima),"
			+ "		<br> will be stored as point ROIs inside the Fiji ROI Manager."
			+ "		<br> This can be used for quality control and manual corrections"
			+ "		<br> with <strong>Load beads center position from ROI Manager</strong> processing option."
			+ "		<br>"
			+ "		<br> Once peak coordinates are generated, complete subvolumes around each peak position"
			+ "		<br> are cropped from the input image. Edge crops, saturated or weak beads, off-center peaks,"
			+ "		<br> and optionally crowded candidates are rejected and summarized in the ImageJ log."
			+ "		<br> Each accepted crop is background-corrected from the median of a 3D outer shell,"
			+ "		<br> converted to 32-bit and normalized to unit integral before PSF averaging."
			+ "		<br>"
			+ "		<br> There are 3 ways to treat the combined beads image stacks:"
			+ "		<br> <strong>median</strong> or <strong>mean average</strong> to generate the PSF image,"
			+ "		<br> or <strong>all beads</strong> image can be kept for further processing."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: It is difficult to locate peak of beads intensity in the OPM raw volume."
			+ "		<br> Hence, the additional deskew step before peak detection step. However, if no deskewing is preferred."
			+ "		<br> One can bypass it by using the <strong>Load ... from ROI Manager</strong> option."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: Candidates whose requested crop touches an image edge are"
			+ "		<br> rejected rather than zero padded, because padding would bias the measured kernel."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: It could also create artefact if the beads are so crowd,"
			+ "		<br> that the inter-beads distance is smaller than the crop volume size."
			+ "		<br> Nearby candidates can be rejected automatically, but a sparse bead preparation is"
			+ "		<br> still recommended for a reliable experimental PSF."
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: In ImageJ, X and Y coordinate indexing is 0-based, while Z slice indexing is 1-based."
			+ "		<br> Please be aware of this when, for example, manual assign Z position of ROI in ROI Manager."
			+ "		<br> In addition, if Z position of a ROI is set to \"0\", it displays on all Z slices." 
			+ "		<br>"
			+ "		<br><strong>Note 5</strong>: Further description on the processing of beads image"
			+ "		<br> can be found in the help text of <strong>prepare beads image</strong> dialog."
			+ "		<br>"
			+ "		<br><strong>Known issue</strong>:If provided rough beads number estimation is higher than the possible peaks"
			+ "		<br> that can be detected in the image or ROI, the peak extraction will return empty."
			+ "		<br> Nothing will shown to specifty this problem currently. This may be improved in the future release.";
	
	
	// help text in html format
	protected static final String PSF_prepare = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deconvolution: Beads Image Preparation</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Prepare beads image to facilitate experimental PSF generation."
			+ "		<br>"
			+ "		<br> The <strong>deskew parameters</strong> will be used if <strong>OPM raw volume</strong> is selected"
			+ "		<br> in <strong>Generate experimental PSF...</strong> dialog."
			+ "		<br> This parameters will be ignored in case of other image type selections."
			+ "		<br>"
			+ "		<br> In the case of <strong>auto detection</strong> image type,"
			+ "		<br> deskew parameters will be estimated as following:"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The XY pixel size will be assumed to be 116 nm, and OPM angle to be 25°."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The Z step size will be calculated as:"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			<strong>XY pixel size * cos(25°) / tan (feature angle).</strong>"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The feature angle is measured from maximum X projection (ZY) view of the input image."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			If interested, one can check this with <strong>Fiji > Analyze > Directonality</strong> command."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			Currently only 10 or 20 Galvo Unit (with 13.24nm per step) cases are accepted."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			If calculated Z step size cannot be rounded to above mentioned range,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			deskew will be aborted and the volume will be processed as it is."
			+ "		<br>"
			+ "		<br> Region of interest (ROI) can be draw onto the input image prior to operation."
			+ "		<br> Then the peak detection will only be performed within the ROI region."
			+ "		<br> Composite ROI is possible by holding \"shift\" key while drawing a 2nd ROI."
			+ "		<br> This enables multiple sub-region selections."
			+ "		<br> Alternatively ROI can be load from .roi or .zip file."
			+ "		<br> This file can be exported from ImageJ ROI Manager, by selecting specific 1 or multiple"
			+ "		<br. ROI entries inside the ROI Manager."
			+ "		<br> Make sure such ROI(s) can be displayed correctly on the designated input beads image."
			+ "		<br> Re-use of ROI from a different image sometimes resulting in out-of-boundary error."
			+ "		<br>"
			+ "		<br> <strong>Z range</strong> extend the selection to Z slices."
			+ "		<br> A range of Z slices can be specified like \"100-200\", so that Z slices outside of this range"
			+ "		<br> will not be considered when extracting 3D local maximas."
			+ "		<br> This is to filter in case some Z slices are systematically much brighter,"
			+ "		<br> and thus make the 3D local maxima detection inaccurate, or fail."
			+ "		<br> Note the Z slices indexing is 1-based, and the range values are inclusive in both beginning and end."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: If <strong>Load ...from ROI Manager</strong> is selected in"
			+ "			<strong>Generate experimental PSF...</strong> dialog,"
			+ "		<br> These parameters are all ignored." 
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>:Load ROI from file option is implemented to support batch processing of many beads image."
			+ "		<br> For example, if the PSF from peripheral region of the Field of View is distorted inhomogeneously,"
			+ "		<br> or if the cover slip cause reflection in the images.";
	
	
	// help text in html format
	protected static final String deconv = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deconvolution: Richard-Lucy Deconvolution</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Deconvolve an image stack with provided PSF."
			+ "		<br>"
			+ "		<br> This command requires two images to be already opened in Fiji:"
			+ "		<br>  - an input image stack that need to be deconvolved,"
			+ "		<br>  - the PSF image (also as stack)."
			+ "		<br>"
			+ "		<br> Two deconvolution methods are available:"
			+ "		<br> <strong>Richardson-Lucy (RL)</strong>, and <strong>Richardson-Lucy Total Variation (RLTV)</strong>."
			+ "		<br>"
			+ "		<br> The <strong>number of iterations</strong> and <strong>regularization factor</strong> are"
			+ "			standard parameters of Richardson-Lucy deconvolution method."
			+ "		<br>"
			+ "		<br> The number of iterations needed is quite subjective and experiment dependent."
			+ "		<br> Typical values could range from 50 to 500."
			+ "		<br> One should test with several different iteration numbers with the data and PSF at hand."
			+ "		<br> Check the quality of deconvolved image, intensity profile, peak values, "
			+ "		<br> and so on to determine the ideal number of iterations."
			+ "		<br>"
			+ "		<br> The regularization factor only matters for Richardson-Lucy Total Variation deconvolution."
			+ "		<br> It is used to suppress noise, and higher value corresponding to higher noise level,"
			+ "		<br> or more smoothing in deconvolved image."
			+ "		<br> To quote from the author:"
			+ "		<br>&nbsp&nbsp&nbsp <em>...My experience has been that anything above 0.005 makes the image too smooth,"
			+ "		<br>&nbsp&nbsp&nbsp	and anything below 0.0001 has not much of an effect...</em>"
			+ "		<br>&nbsp&nbsp&nbsp <a href=\"https://forum.image.sc/t/clij-deconvolution-error/75540/13\">check this discussion on image.sc forum</a>"
			+ "		<br>"
			+ "		<br> Therefore, the regularization factor slider provides a value range in between 0 and 0.005."
			+ "		<br> However, higher values can be directly typed into the numeric field next to it,"
			+ "		<br> and will be taken to perform the Total Variation regularized Richardson-Lucy deconvolution."
			+ "		<br> If the regularization factor set to \"0\", it will be the same as Richard-Lucy deconvolution."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: By default, the current active image will be selected as the input image,"
			+ "		<br> and another image with \"PSF\" keywords in the title will be selected as the PSF image."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: The RL and RLTV deconvolution running on the GPU,"
			+ "			which depends on the <a href=\"https://github.com/clij/clij2-fft\">clij2-fft</a> package."
			+ "		<br> This package is currently still under development by <a href=\"https://forum.image.sc/u/bnorthan\">Brian Northan</a>"
			+ "			with the most recent releases can be found"
			+ "		<a href=\"https://www.dropbox.com/sh/dxofkiyseuxn4l4/AADkIeK3nD5SW7EOsURoQoAGa?e=1&dl=0\">here</a>."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: Deconvolution on volumes that larger than the GPU memory can handel will be partitioned into tiles."
			+ "		<br> Processing status and tile information will be reported to Fiji console. "
			+ "		<br> Although the process is GPU accelerated, it can still take several tens of minutes to even hours to process an OPM dataset. "
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: Make sure the input image and PSF are of the same properties:"
			+ "		<br> i.e.: They need to share the same image acquisition parameters."
			+ "		<br> Both need to be unskewed (raw) volume, or both need to be deskewed with the same deskew setup.";
	

	// help text in html format
	
}
