package de.embl.iclm;

public class Help {

	// help text for deskew active image
	protected static final String deskew = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.5 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2026.08.31 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deskew Image:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Deskew an image stack (as the OPM raw volume) that already opened in Fiji."
			+ "		<br> 3 parameters are essential for the deskewing: the <strong>XY pixel size</strong>,"
			+ "			the <strong>Z step size</strong>, and the <strong>OPM angle</strong>."
			+ "		<br>	With the in house built OPM system at EMBL IC, the typical values are:"
			+ "		<br>"
			+ "		<br>&nbsp <strong> XY pixel size</strong>: 116 nm "
			+ "		<br>&nbsp <strong> Z step size</strong>: 132.5 or 265 nm "
			+ "		<br>&nbsp <strong> OPM angle</strong>: 25°"
			+ "		<br>"
			+ "		<br> These parameters can also be loaded from setup files. "
			+ "			The setup file can be the metadata file normally saved next to the image file with name \"ExperimentalParameters.txt\". "
			+ "			Alternatively the setup file can also be the deskew matrix saved from previous operations,"
			+ "			with name like \"(OPM image name)_deskew.csv\" To save the deskew ( 3D affine transform ) matrix,"
			+ "			use the \"<strong>save deskew setting</strong>\" button located at the bottom of the dialog."
			+ "		<br>"
			+ "		<br> Depending on the input, several options are available to process dual channel images:"
			+ "		<br>"
			+ "		<br><strong> whole image</strong>:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "				No channle separation."
			+ "		<br><strong> fold by midline</strong>:&nbsp&nbsp&nbsp&nbsp"
			+ "				The right half of the image will be folded onto the left side as the 2nd channel."
			+ "		<br><strong> align with SIFT</strong>:&nbsp&nbsp&nbsp"
			+ "				2D rigid transform will be performed on the right half of the image,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "				based on SIFT features, to form the 2nd channel.  "
			+ "		<br><strong>only left</strong>:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"	
			+ "				Only the left half of the image will be processed."
			+ "		<br><strong>only right</strong>:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "				Only the right half of the image will be processed. (no flip of the image)."
			+ "		<br><strong>left & right separately</strong>:&nbsp&nbsp"
			+ "				The input image will be split horizontally in the middle and"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			processed as two independent images."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			(no flip of the right half of the image)."
			+ "		<br>"
			+ "		<br> For the SIFT-based alignment, it would require the input image to have sufficient common features in both channels"
			+ "			(left and right half of the image) to work properly. For example: a beads stack with clear signal in both channels."
			+ "			To save the align ( 2D rigid transform ) matrix,"
			+ "			use the \"<strong>save deskew setting</strong>\" button located at the bottom of the dialog."
			+ "		<br>"
			+ "		<br>2D Projection images can also be created upon selection(s), and displayed following creation of the deskewed 3D volume."
			+ "		<br>"
			+ "		<br>The 3D affine deskew matrix, and/or the 2D rigid align matrix can be exported and re-used later, "
			+ "			with the button \"<strong>save deskew setting</strong>\". Upon clicking, a separate dialog will open and ask for a folder, "
			+ "			in which to save the matrix as .csv files. The file name has a regular expression part <strong>&lt image name&gt</strong>,"
			+ "			that will be replaced with the image name. The matrix will be saved as comma separated values, "
			+ "			which can be read or modified offline."
			+ "		<br>"
			+ "		<br>The <strong>preivew</strong> check box provide live deskew preview features."
			+ "		<br>It would only work with GPU-based processing. Upon previewing,"
			+ "  		the GPU memory will be measured and the input image will be downsampled so that it can fit into the GPU memory,"
			+ "  		in together with the deskewed volume. The downsampling will be equal in X,Y, and Z axis,"
			+ "  		so that the projection views will still reflect the correct geometry."
			+ "		<br>The preview images, both deskewed volume and projection(s),"
			+ "  		should have &quot preview&quot in their image titles."
			+ "  		This keyword is used later to close all previewing images when" 
			+ "  		<strong>OK</strong> or <strong>Cancel</strong> button is pressed."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: The input raw image volume stores slices as time frames."
			+ "			Therefore, The T and Z dimension will be and should be swapped before any operation on the input data."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: The deskew process is 3D affine transformation."
			+ "			The transformation matrix is computed based on the 3 essential input parameters mentioned previously."
			+ "			The transform will be performed on the GPU with CLIJ and imglib2 library, if a suitable GPU is available."
			+ "			If not, or the GPU processing temptation failed, the transform will be performed on CPU, with TransfromJ library."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: It is generally hard to fit the original raw data into GPU all at once."
			+ "  		Therefore, the input volume will be first separated along X axis,"
			+ "			which is the axis that is not changed by the 3D affine transformation."
			+ "  		The X partitions will then be processed on GPU in a sequential manner."
			+ "  		The input partitions and deskewed output partitions will be stored in computer RAM."
			+ "			The deskewed outputs will then be combined together to finish the whole process."
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: The SIFT based alignment parameters are predefined."
			+ "			When computing from input image, an alignment check image will be presented."
			+ "			The image will be a maximum Z projection of deskewed image of 3 channels:"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			&nbsp&nbsp <strong>1</strong>: left side"
			+ "			&nbsp&nbsp <strong>2</strong>: right side flipped"
			+ "			&nbsp&nbsp <strong>3</strong>: right side SIFT aligned"
			+ "		<br> The computed 2D rigid transform matrix will be reported to Fiji console."
			+ "			A description in terms of how much rotation, and translation in X and Y axis"
			+ "			will also be reported. If the rotation exceed 0.5°, or X shfit exceed 80 pixels,"
			+ "			or Y shfit exceed 30 pixels, the alignment would be considered wrong."
			+ "			A warning message will be displayed in Fiji log window."
			+ "			However, the alignment will still be performed."
			+ "			But one should consider using a different sample image,"
			+ "			or use \"fold by midline\" option for channel operation."
			+ "		<br>"
			+ "		<br><strong>Known issue 1</strong>: Live preview might create all white/black images,"
			+ "			This is normally resulting from the Brightness/Contrast setting is not tuned."
			+ "			Often on the first run, or after changes of parameters,"
			+ "			the resulting pixel values are outside the range of curret displaying range"
			+ "		<br>"
			+ "		<br><strong>Known issue 2</strong>: SIFT align with previewing might be not working the same"
			+ "			as the raw input volume, because of the downsampling. "
			+ "			Anyway, the alignment matrix will not be saved with preview run."
			+ "			It only saving with real deskew run, i.e.: <strong>OK</strong> button pressed.";
			
			// help text in html format
	protected static final String batch = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deskew Batch:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Deskew a folder of images."
			+ "		<br>"
			+ "		<br> Select a folder contains all the images that need to be processed."
			+ "		<br> Only \".tif\" and \".tiff\" files will be recognized."
			+ "		<br>	If needed, specify keyword(s) that can be used to filter files by name."
			+ "		<br> Check input folder structure whether it is needed to look for image"
			+ "			files in the subfolders."
			+ "		<br>"
			+ "		<br> The \"deskew image\" checkbox is redundant,"
			+ "			but maybe useful in the future."
			+ "		<br> When, for example, only projection or deconvolution operations "
			+ "			will be needed for batch processing."
			+ "		<br>"
			+ "		<br> The other parameters are the same as in deskew active image case."
			+ "		<br>	Check the help text in <strong>Deskew Image</strong> command for descriptions."
			+ "		<br>"
			+ "		<br><strong>combine as time lapse</strong> "
			+ "			will combine the selected projection images as time-lapse image(s),"
			+ "		<br> and display in Fiji as image stack."
			+ "		<br> The time-lapse image(s) will be updated with the batch processing running,"
			+ "		<br> adding new slice(s) from the most recent generated projection image(s)"
			+ "		<br>"
			+ "		<br> The save path will need to be specified."
			+ "		<br> Or a folder with name \"result\""
			+ "			will be created inside the input folder, to store the result images."
			+ "		<br>"
			+ "		<br> If <strong>separate results to sub-folders</strong> is selected,"
			+ "			A subfolder with name like \"deskew\","
			+ "		<br> or \"maxZ\" will be created to store different type of result images."
			+ "		<br>"
			+ "		<br> In case result is already exist,"
			+ "			it can be skipped or overwritten depending on the choice."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: Operation status will be reported to Fiji console."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: The order of files that would be processed may not be"
			+ "			exactly the same as expected."
			+ "		<br> There is a very basic check based on the file names,"
			+ "			that trying to sort files by recognized numerical part."
			+ "		<br> But it is not implmented to deal with complicate cases,"
			+ "			for example with sub-folder structures and so on."
			+ "		<br> This may result in wrong order of the combined time lapse images."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: Memory should be released automatically"
			+ "			when processing is finished with one file."
			+ "		<br> However, it would be better to monitor the memory usage:"
			+ "		<br> (Plugins &gt Utilities &gt Monitor Memory...)";
	
	
	// help text in html format
	protected static final String watch_folder = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Folder Watcher: setup watcher</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Set up a watcher to monitor a folder for new image file to be created."
			+ "		<br>"
			+ "		<br> Specify a folder that the watcher need to monitor for file changes."
			+ "		<br> It is possible to also process files that already exist in the folder that being watched."
			+ "		<br> The <strong>max file writing delay</strong> defines how long "
			+ "			the watcher will wait from the last FILE MODIFIED event to conclude that"
			+ "			the writting process of the file is completed. And thus can be opened and processed safely."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: sub-folders are ignored from watching."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: A complete file save process normally consist of a FILE CREATED event,"
			+ "		<br> followed by several FILE MODIFED events, while image data are kept writting into the file."
			+ "		<br> Therefore, a delay will be neccessary to identify writing completed files";
	
	
	// help text in html format
	protected static final String watch_process = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Folder Watcher: setup processing</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Set up the processing parameters,"
			+ "		<br> when a new file creation is detected by the folder watcher."
			+ "		<br> The parameters are the same as in <strong>Deskew Batch</strong> command."
			+ "		<br> Check there the help text for a more detailed description of the parameters.";
	
	
	// help text in html format
	protected static final String tcpip = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>TCP-IP Listener:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Set up a listener to receive the full path of file created through TCP-IP socket."
			+ "		<br>"
			+ "		<br> Specify the TCP IP port number that the full file path will be sent through."
			+ "		<br> The rest of the parameters are the same as in <strong>Deskew Batch</strong> command."
			+ "		<br> Check there the help text for a more detailed description of the parameters."
			+ "		<br>"
			+ "		<br><strong>Note</strong>: There is no implementation that closes the listener."
			+ "		<br> Once it's up and running, it will keep listening to the specified port until Fiji exit.";
		
	
	// help text in html format
	protected static final String projection = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Projection:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Create projection image(s) of selected axis with selected type."
			+ "		<br>"
			+ "		<br> It takes an active image that already opened in Fiji as input."
			+ "		<br> The image need to be a 3D image stack."
			+ "		<br>"
			+ "		<br> The projection image(s) created will be labeled with projection axis"
			+ "			and type in the title(s):"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp "
			+ "			e.g.: -maxZ, -minZ, -avgZ, sumZ, -medZ, -stdZ"
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: The projection image(s) will have the same bit depth"
			+ "			as the input image, except for sum projection."
			+ "		<br> Sum projection will be in 32-bit image format to account for large pixel values."
			+ "		<br> Pixel values of the mean and standard deviation projections will be rounded to integer."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: median and standard deviation projection "
			+ "			of X- and Y- axis are not implemented for GPU processing."
			+ "		<br> As a workaround, a permuted volume is first created to transpose the original"
			+ "			X- or Y- axis to the new Z axis."
			+ "		<br> And then a Z projection is performed on GPU to fulfill the desired projection."
			+ "		<br> For X-projection, the ZYX permutation is performed."
			+ "		<br> For Y-projection, the XZY permutation is performed."
			+ "		<br>"
			+ "		<br><strong>Known issue</strong>: "
			+ "		median projection of more than 1000 voxel in the projection axis is not possible on GPU."
			+ "		<br> As a work around a less precise version is implemented as: first compute mean values in small range,"
			+ "		<br> for example every 2 or 3 voxels, and then the median value of these mean values are computed."
			+ "		<br> Median projection on CPU has no such limitation, but normally are slower.";

	
	
	// help text in html format
	protected static final String permutation = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Permutation:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Perform axis permutation on 3D volume."
			+ "		<br>"
			+ "		<br> Flip of axis can be performed prior to axis permutations."
			+ "		<br> The <strong>fold X</strong> option means to fold X axis by midline."
			+ "		<br> This will form a 2-channel image, same to the <strong>fold by midline</strong>"
			+ "		<br> channel option in deskew image command."
			+ "		<br>"
			+ "		<br> The permuted image created will be labeled as such:"
			+ "		<br>&nbsp&nbsp&nbsp <strong> -> Z[X]Y' </strong>"
			+ "			means an original <strong>XYZ</strong> volume permuted to <strong>ZXY</strong> volume."
			+ "		<br>&nbsp&nbsp&nbsp <strong>Y'</strong> means Y axis is flipped prior to permutation."
			+ "		<br>&nbsp&nbsp&nbsp <strong>[X]</strong> means X axis is folded."
			+ "		<br>"
			+ "		<br><strong>Note</strong>: In ImageJ or Fiji, "
			+ "			the default image dimension order is <strong>XY</strong>C<strong>Z</strong>T."
			+ "		<br> For 3D image volume without multiple channel or time frames,"
			+ "		<br> the <strong>1st</strong> axis is <strong>X</strong> axis, "
			+ "			the <strong>2nd</strong> axis is <strong>Y</strong> axis, "
			+ "			and the <strong>3rd</strong> axis is <strong>Z</strong> axis "
			+ "			(still <strong>4th</strong> behind the scene)."
			+ "		<br> upper left corner of the 1st Z slice is recongnized as the coordinate origin."
			+ "		<br> X axis pointing from left to right."
			+ "		<br> Y axis pointing from top to bottom."
			+ "		<br> Z axis pointing from front to back.";
	
	
	// help text in html format
	protected static final String sift = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>SIFT Alignment of Dual-Chnannel OPM Image:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Perform SIFT feature extraction and alignment on 2D images."
			+ "		<br>"
			+ "		<br> Check SIFT feature with parameters:";

	
	
	// help text in html format
	protected static final String transform = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Transform:</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Perform 3D transformations on active image "
			+ "		<br>"
			+ "		<br> This command takes an image that already opened in Fiji,"
			+ "			and perform 3D transformations to it."
			+ "		<br> The transformation could be translation, scaling, rotation,"
			+ "			and shearing, of any specified axis."
			+ "		<br>"
			+ "		<br> Click on the <strong>+</strong> button to add a new transformation option."
			+ "		<br> The new transformation option consist of 5 setup parameters:"
			+ "		<br> &nbsp <strong>apply</strong>: whether to apply the transformation;"
			+ "		<br> &nbsp <strong>transform</strong>: transformation type;"
			+ "		<br> &nbsp <strong>axis</strong>: transformation along which axis;"
			+ "		<br> &nbsp <strong>value</strong>: transformation value;"
			+ "		<br> &nbsp <strong>show result</strong>: whether to display transformed image of this transformation;"
			+ "		<br>"
			+ "		<br> New transformation options can be added right after previous one "
			+ "			by clicking again the <strong>+</strong> button."
			+ "		<br>"
			+ "		<br> If <strong>Apply</strong> button is pressed,"
			+ "			then transformation(s) will be performed from top down,"
			+ "			and display result images for each transformation step that with <strong>show result</strong> checked."
			+ "		<br>"
			+ "		<br> Alternatively if <strong>Apply in Reverse Order</strong> button is pressed,"
			+ "			the transformation(s) will be performed from bottom up."
			+ "		<br>"
			+ "		<br> If <strong>inverse</strong> box is checked,"
			+ "			then the inverse matrix of the combined transformation matrix will be applied."
			+ "		<br>"
			+ "		<br> The transformation options can be saved to .json files in a human readable manner."
			+ "			And can be later loaded back to restore the transformations."
			+ "		<br>"
			+ "		<br> Alternatively the combined transformation matrix can be saved as .csv file."
			+ "			Thus saved transformation matrix file can also be used for deskew operations."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: Translation along X, Y, or Z axis follows ImageJ axis directions."
			+ "			value denotes shift for how many pixels."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: Negative value with scaling along X, Y, or Z axis,"
			+ "			means flip that axis or mirror transformation."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: Rotation along X, Y, or Z axis follows right hand rule."
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp for example: rotation along Z axis means clockwise rotation in the XY plane."
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp value denotes degree of rotation. Negative value then means reverse rotation."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: Shearing need to specify two axis to be clear."
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp Shearing in Y axis along Z axis for value 0.5 means:"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp Y(new) = Y(old) + 0.5* Z(old)"
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: The deskew process of OPM data is basically the sequential result of the following 3 transformations:"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp 1st:&nbsp shear Y along Z for (Z step size * cosθ);"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp 2nd: scale Z for (Z step size * sinθ / XY pixel size);"
			+ "		<br> &nbsp&nbsp&nbsp&nbsp&nbsp 3rd:&nbsp rotate around X for -θ;";
	

	// help text in html format
	protected static final String PSF = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.1.5 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2026.08.31 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deconvolution: Generate PSF from Beads Image(s)</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Average beads from image stack(s) to generate experimental PSF."
			+ "		<br>"
			+ "		<br> It works with either an active image opened in Fiji, or image files saved on disk."
			+ "		<br>"
			+ "		<br> If there's no image open in Fiji, the active image selection option will be omitted."
			+ "		<br> If <strong>load from file</strong> box is checked, active image will also be ignored."
			+ "		<br> The <strong>folder path</strong> expecting a folder that contains the beads image(s)."
			+ "		<br> If <strong>including subfolder(s)</strong> box is checked, "
			+ "		<br> all sub-folders will be recursively searched to locate \".tif\" and \".tiff\" images,"
			+ "		<br> that will be loaded."
			+ "		<br>"
			+ "		<br> <strong>image type</strong> specifies whether the input beads image is deskewed, or not."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The processing steps are different for deskewed and raw volumes:"
			+ "		<br>"
			+ "		<br>&nbsp&nbsp&nbsp	<strong>deskewed volume</strong>: "
			+ "			The local maxima points will be generated directly from the input deskewed volume;"
			+ "		<br>"
			+ "		<br>&nbsp&nbsp&nbsp	<strong>OPM raw volume</strong>:"
			+ "			The input image will first be deskewed, according to parameters in <strong>prepare beads image</strong>."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The local maxima points will be generated from the deskewed volume,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			and mapped back to the raw volume through inveresed transformation."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The crop of sub-volumes surrounding each local maxima locations,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			will thus be performed in the raw OPM volume."
			+ "		<br>"
			+ "		<br>&nbsp&nbsp&nbsp <strong>auto detection</strong>:"
			+ "			will try to check the image type automatically, and determine possible deskew parameters."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			This is based on checking the appearance of the max-projected YZ orthogonal view of the image."
			+ "		<br>"
			+ "		<br> <strong>channel layout</strong> can treat the input as one channel, or split packed"
			+ "		<br> mirrored left/right camera halves into independent channel PSFs. The right half can"
			+ "		<br> be horizontally flipped before bead detection and PSF generation. Files carrying"
			+ "		<br> different <strong>_Channel####</strong> tokens are also averaged independently."
			+ "		<br>"
			+ "		<br>"
			+ "		<br> <strong>prepare beads image</strong> button opens a second dialog"
			+ "			to specify the processing on the beads image(s)."
			+ "		<br>"
			+ "		<br> <strong>Load beads center position from ROI Manager</strong>: is to help semi-manual beads detection."
			+ "		<br> If selected, it will skip all beads detection related steps."
			+ "		<br> Instead, all entries currently presented in ROI Manager will be taken as the beads center position."
			+ "		<br> Therefore, it enables modification and manual selection of beads by user."
			+ "		<br> Please note, it would be better to use point ROI to denote beads center positions."
			+ "		<br> And as the position should be for 3D, also check to make sure the Z slice position is "
			+ "		<br> correctly set and associated with the ROI entries."
			+ "		<br>"
			+ "		<br>"
			+ "		<br> <strong>XY radius</strong> and <strong>Z radius</strong>:"
			+ "			specify the size of each dimension of the beads sub-volumes,"
			+ "		<br> that surrounding the detected local maxima point from previous steps."
			+ "		<br> Note the value here should corresponding to <strong>raiuds</strong>,"
			+ "		<br> The size of such defined volume will be:"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			width:&nbsp X radius ×2 + 1;"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			height: Y radius ×2 + 1;"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			depth:&nbsp Z radius ×2 + 1;"
			+ "		<br> In addition, for the <strong>OPM raw volume</strong> case,"
			+ "			the size will be corresponding to the deskewed volume."
			+ "		<br> This means that after inversed transform back to the coordinates of the raw volume,"
			+ "		<br> the corresponding crop volume will also change."
			+ "		<br> Therefore, the minimum circumscribed bounding box in the raw volume,"
			+ "		<br> that contains the desired deskewed volume will be cropped."
			+ "		<br> There is no manipulation or interpolation of pixel values in this procedure,"
			+ "		<br> but only recalculation of the coordinates and boundaries to be cropped."
			+ "		<br>"
			+ "		<br> <strong>~ bead count</strong>:"
			+ "			indicate the desired beads number within the image, or ROI range."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			It's implemented in a way that even more local maxima are present in the data,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			still roughly the indicated number of peaks will be picked out."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			Peaks with higher SNR are more likely to be detected and kept."
			+ "		<br>"
			+ "		<br> <strong>point to ROI Manager</strong> option only matters for the active image case."
			+ "		<br> Upon checked, coordinates of all the detected peaks (local maxima),"
			+ "		<br> will be stored as point ROIs inside the Fiji ROI Manager."
			+ "		<br> This can be used for quality control and manual corrections"
			+ "		<br> with <strong>Load beads center position from ROI Manager</strong> processing option."
			+ "		<br>"
			+ "		<br> Once peak coordinates are generated, complete subvolumes around each peak position"
			+ "		<br> are cropped from the input image. Edge crops, saturated or weak beads, off-center peaks,"
			+ "		<br> and optionally crowded candidates are rejected and summarized in the ImageJ log."
			+ "		<br> Each accepted crop is background-corrected from the median of a 3D outer shell,"
			+ "		<br> converted to 32-bit and normalized to unit integral before PSF averaging."
			+ "		<br>"
			+ "		<br> There are 3 ways to treat the combined beads image stacks:"
			+ "		<br> <strong>median</strong> or <strong>mean average</strong> to generate the PSF image,"
			+ "		<br> or <strong>all beads</strong> image can be kept for further processing."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: It is difficult to locate peak of beads intensity in the OPM raw volume."
			+ "		<br> Hence, the additional deskew step before peak detection step. However, if no deskewing is preferred."
			+ "		<br> One can bypass it by using the <strong>Load ... from ROI Manager</strong> option."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: Candidates whose requested crop touches an image edge are"
			+ "		<br> rejected rather than zero padded, because padding would bias the measured kernel."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: It could also create artefact if the beads are so crowd,"
			+ "		<br> that the inter-beads distance is smaller than the crop volume size."
			+ "		<br> Nearby candidates can be rejected automatically, but a sparse bead preparation is"
			+ "		<br> still recommended for a reliable experimental PSF."
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: In ImageJ, X and Y coordinate indexing is 0-based, while Z slice indexing is 1-based."
			+ "		<br> Please be aware of this when, for example, manual assign Z position of ROI in ROI Manager."
			+ "		<br> In addition, if Z position of a ROI is set to \"0\", it displays on all Z slices." 
			+ "		<br>"
			+ "		<br><strong>Note 5</strong>: Further description on the processing of beads image"
			+ "		<br> can be found in the help text of <strong>prepare beads image</strong> dialog."
			+ "		<br>"
			+ "		<br><strong>Known issue</strong>:If provided rough beads number estimation is higher than the possible peaks"
			+ "		<br> that can be detected in the image or ROI, the peak extraction will return empty."
			+ "		<br> Nothing will shown to specifty this problem currently. This may be improved in the future release.";
	
	
	// help text in html format
	protected static final String PSF_prepare = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deconvolution: Beads Image Preparation</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Prepare beads image to facilitate experimental PSF generation."
			+ "		<br>"
			+ "		<br> The <strong>deskew parameters</strong> will be used if <strong>OPM raw volume</strong> is selected"
			+ "		<br> in <strong>Generate experimental PSF...</strong> dialog."
			+ "		<br> This parameters will be ignored in case of other image type selections."
			+ "		<br>"
			+ "		<br> In the case of <strong>auto detection</strong> image type,"
			+ "		<br> deskew parameters will be estimated as following:"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The XY pixel size will be assumed to be 116 nm, and OPM angle to be 25°."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The Z step size will be calculated as:"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			<strong>XY pixel size * cos(25°) / tan (feature angle).</strong>"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			The feature angle is measured from maximum X projection (ZY) view of the input image."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			If interested, one can check this with <strong>Fiji > Analyze > Directonality</strong> command."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			Currently only 10 or 20 Galvo Unit (with 13.24nm per step) cases are accepted."
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			If calculated Z step size cannot be rounded to above mentioned range,"
			+ "		<br>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp"
			+ "			deskew will be aborted and the volume will be processed as it is."
			+ "		<br>"
			+ "		<br> Region of interest (ROI) can be draw onto the input image prior to operation."
			+ "		<br> Then the peak detection will only be performed within the ROI region."
			+ "		<br> Composite ROI is possible by holding \"shift\" key while drawing a 2nd ROI."
			+ "		<br> This enables multiple sub-region selections."
			+ "		<br> Alternatively ROI can be load from .roi or .zip file."
			+ "		<br> This file can be exported from ImageJ ROI Manager, by selecting specific 1 or multiple"
			+ "		<br. ROI entries inside the ROI Manager."
			+ "		<br> Make sure such ROI(s) can be displayed correctly on the designated input beads image."
			+ "		<br> Re-use of ROI from a different image sometimes resulting in out-of-boundary error."
			+ "		<br>"
			+ "		<br> <strong>Z range</strong> extend the selection to Z slices."
			+ "		<br> A range of Z slices can be specified like \"100-200\", so that Z slices outside of this range"
			+ "		<br> will not be considered when extracting 3D local maximas."
			+ "		<br> This is to filter in case some Z slices are systematically much brighter,"
			+ "		<br> and thus make the 3D local maxima detection inaccurate, or fail."
			+ "		<br> Note the Z slices indexing is 1-based, and the range values are inclusive in both beginning and end."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: If <strong>Load ...from ROI Manager</strong> is selected in"
			+ "			<strong>Generate experimental PSF...</strong> dialog,"
			+ "		<br> These parameters are all ignored." 
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>:Load ROI from file option is implemented to support batch processing of many beads image."
			+ "		<br> For example, if the PSF from peripheral region of the Field of View is distorted inhomogeneously,"
			+ "		<br> or if the cover slip cause reflection in the images.";
	
	
	// help text in html format
	protected static final String deconv = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>Deconvolution: Richard-Lucy Deconvolution</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Deconvolve an image stack with provided PSF."
			+ "		<br>"
			+ "		<br> This command requires two images to be already opened in Fiji:"
			+ "		<br>  - an input image stack that need to be deconvolved,"
			+ "		<br>  - the PSF image (also as stack)."
			+ "		<br>"
			+ "		<br> Two deconvolution methods are available:"
			+ "		<br> <strong>Richardson-Lucy (RL)</strong>, and <strong>Richardson-Lucy Total Variation (RLTV)</strong>."
			+ "		<br>"
			+ "		<br> The <strong>number of iterations</strong> and <strong>regularization factor</strong> are"
			+ "			standard parameters of Richardson-Lucy deconvolution method."
			+ "		<br>"
			+ "		<br> The number of iterations needed is quite subjective and experiment dependent."
			+ "		<br> Typical values could range from 50 to 500."
			+ "		<br> One should test with several different iteration numbers with the data and PSF at hand."
			+ "		<br> Check the quality of deconvolved image, intensity profile, peak values, "
			+ "		<br> and so on to determine the ideal number of iterations."
			+ "		<br>"
			+ "		<br> The regularization factor only matters for Richardson-Lucy Total Variation deconvolution."
			+ "		<br> It is used to suppress noise, and higher value corresponding to higher noise level,"
			+ "		<br> or more smoothing in deconvolved image."
			+ "		<br> To quote from the author:"
			+ "		<br>&nbsp&nbsp&nbsp <em>...My experience has been that anything above 0.005 makes the image too smooth,"
			+ "		<br>&nbsp&nbsp&nbsp	and anything below 0.0001 has not much of an effect...</em>"
			+ "		<br>&nbsp&nbsp&nbsp <a href=\"https://forum.image.sc/t/clij-deconvolution-error/75540/13\">check this discussion on image.sc forum</a>"
			+ "		<br>"
			+ "		<br> Therefore, the regularization factor slider provides a value range in between 0 and 0.005."
			+ "		<br> However, higher values can be directly typed into the numeric field next to it,"
			+ "		<br> and will be taken to perform the Total Variation regularized Richardson-Lucy deconvolution."
			+ "		<br> If the regularization factor set to \"0\", it will be the same as Richard-Lucy deconvolution."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: By default, the current active image will be selected as the input image,"
			+ "		<br> and another image with \"PSF\" keywords in the title will be selected as the PSF image."
			+ "		<br>"
			+ "		<br><strong>Note 2</strong>: The RL and RLTV deconvolution running on the GPU,"
			+ "			which depends on the <a href=\"https://github.com/clij/clij2-fft\">clij2-fft</a> package."
			+ "		<br> This package is currently still under development by <a href=\"https://forum.image.sc/u/bnorthan\">Brian Northan</a>"
			+ "			with the most recent releases can be found"
			+ "		<a href=\"https://www.dropbox.com/sh/dxofkiyseuxn4l4/AADkIeK3nD5SW7EOsURoQoAGa?e=1&dl=0\">here</a>."
			+ "		<br>"
			+ "		<br><strong>Note 3</strong>: Deconvolution on volumes that larger than the GPU memory can handel will be partitioned into tiles."
			+ "		<br> Processing status and tile information will be reported to Fiji console. "
			+ "		<br> Although the process is GPU accelerated, it can still take several tens of minutes to even hours to process an OPM dataset. "
			+ "		<br>"
			+ "		<br><strong>Note 4</strong>: Make sure the input image and PSF are of the same properties:"
			+ "		<br> i.e.: They need to share the same image acquisition parameters."
			+ "		<br> Both need to be unskewed (raw) volume, or both need to be deskewed with the same deskew setup.";
	

	// help text in html format
	protected static final String debug = "<html>"
			+ "		<h2>OPM Toolset (ImageJ plugin)</h2>"
			+ "		version: 2.0.0 <br>"
			+ "		date:&nbsp&nbsp&nbsp&nbsp 2024.03.26 <br>"
			+ "		author:&nbsp Ziqiang.Huang@embl.de <br>"
			+ "		<h2>debug</h2> "
			+ "		<h3>Usage:</h3> "
			+ "			Usage description."
			+ "		<br>"
			+ "		<br> Parameter description."
			+ "		<br>"
			+ "		<br><strong>Note 1</strong>: Note 1 description.";	
	
}
